---
before_install:
  - "git fetch --tags"

scala_212: &scala_212 2.12.10
scala_213: &scala_213 2.13.1

language: scala

cache:
  directories:
    - $HOME/.coursier/cache
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot
dist: xenial

stages:
  - name: test
  - name: release
    if: "((branch = main AND type = push) OR (tag IS present)) AND NOT fork"

jobs:
  include:
    - &all_tests
      stage: test
      env: TEST="all_tests"
      script: sbt test
      scala: *scala_212
    - <<: *all_tests
      env: TEST="all_tests"
      scala: *scala_213
    - env: TEST="styling"
      scala: *scala_213
      script: sbt ++$TRAVIS_SCALA_VERSION scalafmtCheckAll
    - stage: release
      script: sbt ci-release
  allow_failures:
    - scala: *scala_212
      env: TEST="all_tests"
